### ISSUE TITLE
Vimeo jQuery API not working anymore / Vimeo update?

### ISSUE THREAD

**Issue by jmbelloteau** [jrue/Vimeo-jQuery-API#11]
Hello,

First, just a big thank for your script! Your code is fantastic and so simple to use... No more need to use froogaloop and that's a very good news.

I'm sorry to ask here but I didn't found your email. The link trough your website is not working.

Actually I use your code for my personnal website (beta-testing now), you can see it here:

http://s346204871.onlinehome.fr/demoreels.php

Here is the code of my script, do you think it's possible to shrink/optimise it?

HTML

<section class="demoreels">

	<div class="responsvid">
		<div class="responsvid_cover dop">
			<div class="flowtype_demoreel"><h1>cinematographer<span>demoreel</span></h1><i class="ion-ios-play-outline"></i></div>
			<div class="overlay"></div>
		</div>
		<div class="video_container">
			<iframe id="dop_demoreel" src="https://player.vimeo.com/video/120206922?api=1&player_id=dop_demoreel" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
		</div>
	</div>
	
	<div class="responsvid">
		<div class="responsvid_cover colorist">
			<div class="flowtype_demoreel"><h1>colorist<span>demoreel</span></h1><i class="ion-ios-play-outline"></i></div>
			<div class="overlay"></div>
		</div>
		<div class="video_container">
			<iframe id="colorist_demoreel" src="https://player.vimeo.com/video/120206922?api=1&player_id=colorist_demoreel" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
		</div>
	</div>
	
</section>

SCRIPT

	var animSpeed = 0;

	$('.dop').click(function () {
		$(this).fadeOut(animSpeed);
		$('.video_container').fadeIn(animSpeed);
		$("#dop_demoreel").vimeo("play");
		$("#colorist_demoreel").vimeo("pause");
	});
	$("#dop_demoreel").on("pause", function () {
		$('.dop').fadeIn(animSpeed);
		$("#dop_demoreel").vimeo("unload");
	});
	$("#dop_demoreel").on("finish", function () {
		$('.dop').fadeIn(animSpeed);
		$("#dop_demoreel").vimeo("unload");
	});

	$('.colorist').click(function () {
		$(this).fadeOut(animSpeed);
		$('.video_container').fadeIn(animSpeed);
		$("#colorist_demoreel").vimeo("play");
		$("#dop_demoreel").vimeo("pause");
	});
	$("#colorist_demoreel").on("pause", function () {
		$('.colorist').fadeIn(animSpeed);
		$("#colorist_demoreel").vimeo("unload");
	});
	$("#colorist_demoreel").on("finish", function () {
		$('.colorist').fadeIn(animSpeed);
		$("#colorist_demoreel").vimeo("unload");
	});

Thank you a lot.

Jim

**Comment by jmbelloteau** [comment]
I use chrome to test and got this error in the console :

ConsoleAgent: Uncaught SyntaxError: Unexpected token < (url: http://localhost:8888/app/libs/js/vimeoapi.min.js)

ConsoleAgent: Uncaught TypeError: $(...).vimeo is not a function (url: http://localhost:8888/app/js/main.min.js) in :868

**Comment by jrue** [comment]
It's a very nice website, and stunning videos. 

It seems to be working for me when I play one video, the other stops. 

Vimeo did do some sort of update where they now require https connections and I've updated the repo to reflect that. Not sure if this was the issue you were having.

**Comment by icyflame** [comment]
@jmbelloteau Fwiw, I just used this plugin, and it is working fine.

***

cc / @jrue

**Comment by rootion** [comment]
Hello, I didnt want to create a new post to say the same thing, but I just forked the repository and I dont manage to get the example.html to work. Should I create a new issue to report this?

I've got the following html:
```html
    <iframe id="video_01" src="https://player.vimeo.com/video/77889659?api=1&amp;player_id=video_01" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
```

and this jquery script:
```javascript
$(document).ready(function($) {
    $("#myvideo").vimeo("play");
});
```
but its not playing when loading the page.

Is it because I am running it locally?

**Comment by icyflame** [comment]
@rootion The ID of the iframe is `video_01` and not `myvideo`. You have referenced `#myvideo` in the jQuery script. Please try after fixing this.
