### ISSUE TITLE
script should not assume page contains #myvideo

### ISSUE THREAD

**Issue by mediaformat** [jrue/Vimeo-jQuery-API#12]
To facilitate CMS integration API should not assume page contains #myvideo even if it is referenced in a script.js.

I am referencing #myvideo in a generic script.js file, included in all pages.
The problem is I am getting `Uncaught TypeError: Cannot read property 'toLowerCase' of undefined` on pages where there is no  iframe#myvideo.

**Comment by jrue** [comment]
There is no reference to `#myvideo` in my script. I think you might be using the demo example, or referencing your own placeholder ids?

https://github.com/jrue/Vimeo-jQuery-API/tree/master/dist

When you invoke the `.vimeo()` command, it does general checks to make sure its receiving messages from Vimeo, or that the src of the iframe contains "vimeo.com." Maybe there is a conflict with some mention of vimeo in the src, but it's not actually a vimeo video?

Without seeing the script, I'm not certain what is causing this error. I can add additional checks... but hate to bloat the code unnecessarily. But for CMS integration, I'd be happy to add some checks.

Maybe paste a snippet of where you're calling `vimeo()`?

**Comment by mediaformat** [comment]
At the end of the day, my script just needed a bit of extra logic around it...
```
if($("#myvideo").length > 0) {
  $("#myvideo").vimeo("play");
}
```
