### ISSUE TITLE
Documentation for "ready" event

### ISSUE THREAD

**Issue by jrobson153** [jrue/Vimeo-jQuery-API#16]
Hey there!

This is not a bug, only a documentation enhancement. In Froogaloop there is a "ready" event that gets fired once the iframe is loaded, very handy in certain scenarios. I notice that there doesn't seem to be any documentation of this event being handled by your plugin, but when I tested it the event fires just fine.

So doing something like this:
```js
$("#myvideo").on("ready", function(){
    console.log( 'iframe is ready!' );
});
```

Works great, and is only fired once the iframe is loaded. Thought you might want to add that under the "events" documentation in the Readme.

Great plugin by the way!

**Comment by jrue** [comment]
Thanks. Just added it.
