### ISSUE TITLE
No Events, but methods work

### ISSUE THREAD

**Issue by lphomiej** [jrue/Vimeo-jQuery-API#18]
I am trying to send an event when someone plays the Vimeo video.

I tested your plugin with the play command and it works correctly, playing the video. I can also pause, set volume, etc.

For example, this works fine:
```javascript
$("#vimeo_player").vimeo("setVolume", 0.5);
```
However, I cannot 'hear' any of the messages. My code to test it is simple:
```javascript
$(window).on("message", function(e){
    console.log(e);
});
```
Also tried listening to the iFrame itself, but no luck:
```javascript
$("#vimeo_player").on("message", function(e){
    console.log(e);
});
```
Any ideas?

**Comment by despecial** [comment]
I can confirm it stopped working. Last month there weren't problems checking the "Play" state but now there is no feedback.

**Comment by jrue** [comment]
You can't ask for messages on the iframe, only on the window object. This is automatically built into the plugin, so you shouldn't need to do this unless you're debugging.

```javascript
$(window).on("message", function(e){
    console.log(e);
});
```

I just made an update to the plugin, in case you were doing this because something wasn't working.
