### ISSUE TITLE
.vimeo.play('playerId') not working on iOS9

### ISSUE THREAD

**Issue by afisher88** [jrue/Vimeo-jQuery-API#20]
I am trying to create a play button using the API.

I have a function that creates a play handler here:

```
function registerPlayHandler(playerId) {

  var playBtn = $('#video-play');

  if(playBtn.length > 0) {
    playBtn.removeClass('hidden');

    playBtn.on('click', function() {
      $(playerId).vimeo('play');

      console.log(playerId);
    });
  }
}
```

I then pass this the ID of the player inside of a $(window).load() function. This works fine on desktop devices but on Safari on iOS9 nothing happens. I can log out the playerId on the click function when remote debugging but the play part of the function has no effect.

$(playerId).length I get a value of 1 so the iframe must be on the page at this point.

**Comment by jrue** [comment]
This appears to be a restriction with the way iOS works. You cannot initiate videos with anything other than the built-in Vimeo play button. However events do fire, like playProgress and finish. I've updated the readme to include this disclaimer.
