### ISSUE TITLE
setVimeoAPIurl: window.location.protocol https fix

### ISSUE THREAD

**Issue by ryanmac** [jrue/Vimeo-jQuery-API#3]
window.location.protocol returns "http:" or "https:", not "http" or "https".

change setVimeoAPIurl:
return window.location.protocol !== 'https' ? 'http:'+d.attr('src').split('?')[0] : 'https:'+d.attr('src').split('?')[0];

to:
return window.location.protocol !== 'https:' ? 'http:'+d.attr('src').split('?')[0] : 'https:'+d.attr('src').split('?')[0];

**Comment by jrue** [comment]
Thanks, nice catch. This has been fixed.
