### ISSUE TITLE
For multi Vimeo Videos, this API doesn't work

### ISSUE THREAD

**Issue by winman826** [jrue/Vimeo-jQuery-API#30]
For one vimeo video, this API works well, but For multi videos this doesn't work.
Of course, I followed all configuration( like custom manual variables ) as your document, but it doesn't help at all.
All events don't work for 2nd video( next video, as well ).
Please check the test link:
https://wyzi.fivedime.nyc/

**Comment by jrue** [comment]
Hi @winman826, this library is deprecated, and no longer updated. I would encourage you to use the new official javaScript library from Vimeo, which replicates most of what I tried to do with this plugin. [https://github.com/vimeo/player.js](https://github.com/vimeo/player.js)

Thanks for your interest in this project.
