### ISSUE TITLE
You must pass either a valid element or a valid id

### ISSUE THREAD

**Issue by cbrasser** [jrue/Vimeo-jQuery-API#31]
I tried using your API to simply queue up multiple vimeo videos, however I cannot event play a single video without getting the aforementioned error.

I copied the exact iframe from your example.html:

`  <iframe width="1200" height="675" wmode="transparent" id="video" src="https://player.vimeo.com/video/448509282?background=0&title=0&amp;byline=0&amp;portrait=0&amp;color=ffffff&amp;autoplay=0&amp;api=1&amp;player_id=player_1&amp;hd=1"></iframe>`

**Comment by jrue** [comment]
Hi cbrasser, this API is no longer supported. Vimeo changed their API and you should now use the official one on their site. [https://github.com/vimeo/player.js](https://github.com/vimeo/player.js)

Best, J
