### ISSUE TITLE
playProgress not firing

### ISSUE THREAD

**Issue by gil--** [jrue/Vimeo-jQuery-API#5]
I am able to get values returned from the API Methods such as getVideoUrl. However, I have been unable to get *playProgress* to return anything. Here is my code:
```
jQuery(document).ready(function($) {
    
    var progress = 0;
    var userProgress = 100; //example user data retrieved from DB
    var lastUpdateProgress = 0;
    var videoUrl;

    $("#player_1").vimeo("getVideoUrl", function(data){
        videoUrl = data;
        console.log(videoUrl);
    });

    if(userProgress) {
        $("#player_1").vimeo("seekTo", userProgress).vimeo("pause"); // DESKTOP only.
    }

    $("#player_1")
    .on("pause", function(){
        console.log('paused'); //FOR DEBUG
        updateProgress();
    })
    .on("finish", function(){
        console.log('finished'); //FOR DEBUG
    })
    .on("playProgress", function(d){
        console.log(d.seconds + 's played'); //FOR DEBUG

        // Update progress when video was paused
        if(d.seconds > progress) {
            progress = d.seconds;  
        }
    });

    // Every 5 seconds, update progress
    setInterval(updateProgress, 5000);

    function updateProgress() {
        // $.post('/callback', {
        //     progress: progress
        // });

        if (lastUpdateProgress == progress) {
            return;
        }

        console.log('Data saved:' + progress); //FOR DEBUG
        lastUpdateProgress = progress;
    }

});
```

Any idea why? Everything else seems to work apart from playProgress which is actually the one method I REALLY need.

**Comment by jrue** [comment]
Oh wow, I found the error and updated the repo, along with new tags and release version. Thanks for catching this!

**Comment by gil--** [comment]
I updated to latest version and playProgress now fires but when retrieving d.seconds it's undefined and logging out d gives:
![screen shot 2015-03-10 at 10 37 39 am](https://cloud.githubusercontent.com/assets/3484527/6577063/87a6636e-c711-11e4-943d-62d64718d90c.png)

I don't understand what's wrong that's causing the data to be undefined as the expected output according to the docs is
```
//{
//  "seconds"  : "4.308",
//  "percent"  : "0.012",
//  "duration" : "359.000"
//}
```

**Comment by jrue** [comment]
Ah, I had incorrect information in the example and readme. I've updated the documentation.

In your case the first argument was the event being fired, and a second argument would be the actual data object, with seconds, etc. So `function(event, data){ ... }` is what you want.

```javascript
$("#myvideo").on("playProgress", function(evt, data){

        console.log(data.seconds + 's played'); //FOR DEBUG

        // Update progress when video was paused
        if(data.seconds > progress) {
            progress = data.seconds;  
        }
});
```
I've updated the documentation.
