### ISSUE TITLE
Better way for you to handle multiple videos

### ISSUE THREAD

**Issue by drewbaker** [jrue/Vimeo-jQuery-API#8]
I noticed you do this:

```
 setPlayerID : function(d){ ... },
```

You should loop through all present Vimeo iframes on the page, assign each an ID like "vimeo-video-1", "vimeo-video-2" etc, then append that to the URL. That way you will support multiple Vimeo videos on a page always. You'd want some conditionals like you have in case the users has assigned something already.

PS: Are you based in Los Angeles by any chance? We are one of the biggest Vimeo Pro users in the country I suspect (www.funkhaus.us).

**Comment by jrue** [comment]
Yeah, i remember thinking of this at one point. Does changing the src value of the iframes to append a query string to the URLs cause the content to reload? I'll do some testing to find out. It would be convenient for the plugin to do this and make it more plug-and-play.

**Comment by drewbaker** [comment]
@jrue yes changing the SRC on an iFrame will trigger a reload of the content. So make sure you do all of that before binding any events etc. 

It's worth noting that the way Vimeo loads videos in an iFrame actually runs later than jQuery(document).ready(), so anything you do won't actually cause a content reload that the user will notice. We use it all the time, and it's fine.

**Comment by figbomb** [comment]
Came up with a little mock-up for this

````
 $('iframe').each(function(index){
	 	var videoIndex = '?' + 'vimeoVideo-' + index,
	 	src = $(this).attr('src');
	 	$(this).attr('src', src + videoIndex);
	 });
````

**Comment by drewbaker** [comment]
@figbomb that looks about right, but I think it would be worth checking if 'src' already had the ? query string in it, because some embeds will already have that.

**Comment by jrue** [comment]
I won't be able to get to this until this weekend. But I already have a check in there.

Vimeo sends window messages with a "player_id" property if they have it set in as a URL query string. So we check if the data has a property "player_id" with this line `if(d.hasOwnProperty("player_id"))`

If it *does* have that property, then we first check to see if they gave the iframe id the same name as recommended by documentation `if($("#" + d.player_id).length)` otherwise, just find any iframe with the player_id in the src attribute `$("iframe[src*=" + d.player_id + "]");`.

```javascript
if(d.hasOwnProperty("player_id")){
    if($("#" + d.player_id).length){
        return $("#" + d.player_id);
    } else {
        return $("iframe[src*=" + d.player_id + "]");
    }
} else {

//No player_id. Use the first Vimeo video on the page, and hope they don't have multiples
    return $("iframe[src*='vimeo']").eq(0);
}
```
But, I do need to redo this.

Cycling through every iframe could be problematic, because they might have Google Maps or other non-vimeo iframes in the code. So we could do something like:

```javascript
$("iframe[src*='vimeo']").each(function(index){

    if($(this).attr('src').match(/player_id/g) === null){
        //append a unique id query string.
    }

});
```

I also have a check for ready messages from Vimeo which might have to be reinitiated. I'll go through the whole thing this weekend and do a pre-release. But once it's done, it will be much more plug-and-play.

**Comment by jrue** [comment]
OK. I added support for multiple videos automatically. This should greatly improve things when using this in environments like WordPress.

I added the code to a branch for now until I can really user-test this. Later, I'll merge it into a standard release. If you guys have some time to test it out, that would be great. 

https://github.com/jrue/Vimeo-jQuery-API/tree/8-multiple-videos/dist

I'll have my students test it out as well. I ran various tests using multiple videos, and I couldn't find any issues. It seems to work great from what I could tell. Let me know if you find anything.

Here is how it works:

1. Go through every vimeo iframe on the page, and see if it has "player_id" in the src attribute. If not, append it and reload the iframe.

2. If it has "player_id" already, then proceed as normally without reloading (most efficient process.)

Thanks for your suggestions and help.

**Comment by jrue** [comment]
Tested without issue. Updated readme with new info and published to main repo.

**Comment by figbomb** [comment]
Great job @jrue! Thanks again for the great API.

**Comment by drewbaker** [comment]
@jrue I think I found a bug with this update.

> Go through every vimeo iframe on the page, and see if it has "player_id" in the src attribute. If not, append it and reload the iframe.

If the the src attribute does not contain a a "player_id", you will also need to add a matching Id attribute to the iFrame. The elements id and the player_id need to match, like so:

```
<iframe id="needs-to-match" src="//player.vimeo.com/video/77889659?api=1&player_id=needs-to-match"></iframe>
```

**Comment by figbomb** [comment]
Not sure if this will solve your problem or not, but this is how I used the plugin with Wordpress. My code might be too rigid to be of immediate use, but maybe it will help.

```` 
$('iframe').each(function(index){
        var videoID = "video" + index;
        $(this).attr('id',videoID);
        var videoIndex = '?&api=1&player_id=video' + index,
        src = $(this).attr('src');
        $(this).attr('src', src + videoIndex);
     });

$('*[id*=video]').each(function(){
      $(this).on('play',playVideo);
      $(this).on('pause',stopVideo);
   });
````

But like I said, this could definitely be improved upon.
